import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID,createHash} from 'node:crypto';
import {initializeApp,deleteApp} from 'firebase/app';
import {getAuth,connectAuthEmulator,signInWithEmailAndPassword} from 'firebase/auth';
import {getFunctions,connectFunctionsEmulator,httpsCallable} from 'firebase/functions';
import {getFirestore,connectFirestoreEmulator,doc,getDoc,terminate} from 'firebase/firestore';
import {getStorage,connectStorageEmulator,ref,getBytes} from 'firebase/storage';
import {createRequire} from 'node:module';
const serverRequire=createRequire(new URL('../functions/package.json',import.meta.url));
const sharp=serverRequire('sharp');
const {initializeApp:adminApp,deleteApp:deleteAdmin}=serverRequire('firebase-admin/app');
const {getAuth:adminAuth}=serverRequire('firebase-admin/auth');
if(!process.env.FIREBASE_AUTH_EMULATOR_HOST||!process.env.FIRESTORE_EMULATOR_HOST||!process.env.FIREBASE_STORAGE_EMULATOR_HOST)throw new Error('Emulators required.');
const projectId='demo-riwaayat',admin=adminApp({projectId}),apps=[];
async function session(uid,verified){
 const email=`${uid}@example.test`,password=randomUUID();await adminAuth(admin).createUser({uid,email,password,emailVerified:verified});
 const app=initializeApp({projectId,apiKey:'demo-key',storageBucket:`${projectId}.appspot.com`},uid);apps.push(app);
 const auth=getAuth(app);connectAuthEmulator(auth,'http://127.0.0.1:9098',{disableWarnings:true});
 const db=getFirestore(app);connectFirestoreEmulator(db,'127.0.0.1',8086);
 const functions=getFunctions(app);connectFunctionsEmulator(functions,'127.0.0.1',5002);
 const storage=getStorage(app);connectStorageEmulator(storage,'127.0.0.1',9198);
 await signInWithEmailAndPassword(auth,email,password);return {db,functions,storage};
}
try{
 const alice=await session(`owner-${randomUUID()}`,true),bob=await session(`other-${randomUUID()}`,true),unverified=await session(`new-${randomUUID()}`,false);
 const uid=getAuth(apps[0]).currentUser.uid;
 const input={requestId:randomUUID(),title:'Emulator wedding',templateId:'noor'};
 await test('client cannot supply an owner or publish status',async()=>{await assert.rejects(()=>httpsCallable(alice.functions,'createDraft')({...input,ownerId:'someone-else',status:'published'}),e=>e.code==='functions/invalid-argument');});
 await test('unverified user cannot create a draft',async()=>{await assert.rejects(()=>httpsCallable(unverified.functions,'createDraft')(input),e=>e.code==='functions/permission-denied');});
 await test('create draft persists once and rejects conflicting retries',async()=>{const call=httpsCallable(alice.functions,'createDraft');assert.equal((await call(input)).data.id,input.requestId);assert.equal((await call(input)).data.id,input.requestId);const saved=await getDoc(doc(alice.db,`owners/${uid}/events/${input.requestId}`));assert.equal(saved.data().status,'draft');assert.equal(saved.data().ownerId,uid);assert.equal(saved.data().content,null);await assert.rejects(()=>call({...input,title:'Conflicting retry'}),e=>e.code==='functions/already-exists');});
 const image=await sharp({create:{width:30,height:20,channels:3,background:'#aabbcc'}}).png().toBuffer();const photo={eventId:input.requestId,requestId:randomUUID(),base64:image.toString('base64')};
 await test('cross-user upload is rejected',async()=>{await assert.rejects(()=>httpsCallable(bob.functions,'uploadPhoto')(photo),e=>e.code==='functions/not-found');});
 await test('invalid image is rejected before storage',async()=>{await assert.rejects(()=>httpsCallable(alice.functions,'uploadPhoto')({...photo,base64:Buffer.from('invalid image').toString('base64')}),e=>e.code==='functions/invalid-argument');});
 await test('photo is normalized, private and retry-safe',async()=>{const call=httpsCallable(alice.functions,'uploadPhoto');const result=(await call(photo)).data;assert.equal((await call(photo)).data.path,result.path);const bytes=await getBytes(ref(alice.storage,result.path));assert.equal((await sharp(Buffer.from(bytes)).metadata()).format,'webp');await assert.rejects(()=>getBytes(ref(bob.storage,result.path)));const saved=await getDoc(doc(alice.db,`owners/${uid}/events/${input.requestId}`));assert.equal(saved.data().photoCount,1);});

 const guestApp=initializeApp({projectId,apiKey:'demo-key'},'guest-'+randomUUID());apps.push(guestApp);const guestFunctions=getFunctions(guestApp);connectFunctionsEmulator(guestFunctions,'127.0.0.1',5002);const guestDb=getFirestore(guestApp);connectFirestoreEmulator(guestDb,'127.0.0.1',8086);
 const content={couple:'Test Couple',intro:'Welcome',note:'Join us',quote:'Our story',startsAt:'2026-12-20T17:00:00+05:00',timeZone:'Asia/Karachi',hashtag:'#Test',dressCode:'Formal',venue:{name:'Sample venue',address:'Sample address',mapQuery:'Lahore'},story:[],ceremonies:[],imagePhotoId:photo.requestId,galleryPhotoIds:[photo.requestId],instrument:'Oud',particle:'stars',effects:{opening:true,particles:true,music:false,scratch:true}};
 const save={eventId:input.requestId,requestId:randomUUID(),revision:0,title:input.title,content};
 const invoke=(name,data)=>httpsCallable(alice.functions,name)(data);const guest=(name,data)=>httpsCallable(guestFunctions,name)(data);
 await test('draft content is unavailable to guests and other owners',async()=>{await assert.rejects(()=>guest('getInvitation',{id:input.requestId}),e=>e.code==='functions/not-found');await assert.rejects(()=>httpsCallable(bob.functions,'saveDraft')(save),e=>e.code==='functions/not-found');});
 await test('saving is versioned, retry-safe and validates photos and timezone',async()=>{await assert.rejects(()=>invoke('saveDraft',{...save,content:{...content,timeZone:'Invalid/Zone'}}),e=>e.code==='functions/invalid-argument');await assert.rejects(()=>invoke('saveDraft',{...save,content:{...content,imagePhotoId:randomUUID()}}),e=>e.code==='functions/failed-precondition');assert.equal((await invoke('saveDraft',save)).data.revision,1);assert.equal((await invoke('saveDraft',save)).data.revision,1);await assert.rejects(()=>invoke('saveDraft',{...save,requestId:randomUUID()}),e=>e.code==='functions/aborted');});
 const publishing={eventId:input.requestId,requestId:randomUUID(),revision:1,access:'passcode',passcode:'Local-Guest-2026'};let privateToken;
 await test('passcode gate returns no content and published documents stay unreadable',async()=>{await invoke('publishInvitation',publishing);assert.deepEqual((await guest('getInvitation',{id:input.requestId})).data,{locked:true});await assert.rejects(()=>guest('getInvitation',{id:input.requestId,passcode:'wrong-password'}),e=>e.code==='functions/permission-denied');await assert.rejects(()=>getDoc(doc(guestDb,'published',input.requestId)));const result=(await guest('getInvitation',{id:input.requestId,passcode:publishing.passcode})).data;assert.equal(result.content.couple,'Test Couple');assert.equal(result.passwordHash,undefined);assert.equal(result.ownerId,undefined);privateToken=result.token;});
 await test('saved edits do not change the published snapshot',async()=>{await invoke('saveDraft',{...save,requestId:randomUUID(),revision:1,content:{...content,note:'New draft message'}});const guestView=(await guest('getInvitation',{id:input.requestId,passcode:publishing.passcode})).data;assert.equal(guestView.content.note,'Join us');publishing.revision=2;});
 await test('guest media requires scoped session and only selected photos are accessible',async()=>{assert.ok((await guest('getInvitationPhoto',{id:input.requestId,token:privateToken,photoId:photo.requestId})).data.base64);await assert.rejects(()=>guest('getInvitationPhoto',{id:input.requestId,token:'0'.repeat(64),photoId:photo.requestId}),e=>e.code==='functions/permission-denied');await assert.rejects(()=>guest('getInvitationPhoto',{id:input.requestId,token:privateToken,photoId:randomUUID()}),e=>e.code==='functions/permission-denied');});
 await test('republishing public access invalidates old guest sessions',async()=>{await invoke('publishInvitation',{eventId:publishing.eventId,revision:publishing.revision,requestId:randomUUID(),access:'public'});await assert.rejects(()=>guest('getInvitationPhoto',{id:input.requestId,token:privateToken,photoId:photo.requestId}),e=>e.code==='functions/permission-denied');assert.equal((await guest('getInvitation',{id:input.requestId})).data.locked,false);await assert.rejects(()=>invoke('restoreInvitation',{eventId:input.requestId,requestId:randomUUID()}),e=>e.code==='functions/failed-precondition');});
 const action={eventId:input.requestId,requestId:randomUUID()};
 await test('duplication is owner-only and creates a private copy',async()=>{await assert.rejects(()=>httpsCallable(bob.functions,'duplicateInvitation')(action),e=>e.code==='functions/not-found');const copy=(await invoke('duplicateInvitation',action)).data;assert.equal((await invoke('duplicateInvitation',action)).data.id,copy.id);const saved=await getDoc(doc(alice.db,`owners/${uid}/events/${copy.id}`));assert.equal(saved.data().status,'draft');assert.equal(saved.data().content.couple,'Test Couple');await assert.rejects(()=>guest('getInvitation',{id:copy.id}),e=>e.code==='functions/not-found');});
 await test('unpublish and archive stop guest access; restore stays private',async()=>{await invoke('unpublishInvitation',action);await assert.rejects(()=>guest('getInvitation',{id:input.requestId}),e=>e.code==='functions/not-found');await invoke('publishInvitation',{eventId:publishing.eventId,revision:publishing.revision,requestId:randomUUID(),access:'public'});await invoke('archiveInvitation',action);await assert.rejects(()=>guest('getInvitation',{id:input.requestId}),e=>e.code==='functions/not-found');await assert.rejects(()=>invoke('saveDraft',{...save,revision:1,requestId:randomUUID()}),e=>e.code==='functions/not-found');await invoke('restoreInvitation',action);await invoke('restoreInvitation',action);assert.equal((await getDoc(doc(alice.db,`owners/${uid}/events/${input.requestId}`))).data().status,'draft');});

 await invoke('publishInvitation',{eventId:input.requestId,revision:2,requestId:randomUUID(),access:'public'});
 const replyToken=(await guest('getInvitation',{id:input.requestId})).data.token;
 const rsvp={id:input.requestId,token:replyToken,requestId:randomUUID(),name:'Sample Guest',attendance:'yes',partySize:3,meal:'Vegetarian',ceremonies:[],note:'Private host note'};
 await test('RSVP persists once and increments totals only once',async()=>{const result=(await guest('submitRSVP',rsvp)).data;assert.equal(result.saved,true);await guest('submitRSVP',rsvp);const saved=await getDoc(doc(alice.db,`owners/${uid}/events/${input.requestId}/rsvps/${rsvp.requestId}`));assert.equal(saved.data().note,'Private host note');const event=await getDoc(doc(alice.db,`owners/${uid}/events/${input.requestId}`));assert.equal(event.data().rsvpStats.guests,3);assert.equal(event.data().rsvpStats.replies,1);await assert.rejects(()=>guest('submitRSVP',{...rsvp,name:'Changed retry'}),e=>e.code==='functions/already-exists');});
 await test('private replies cannot be read by guests or other hosts',async()=>{const path=`owners/${uid}/events/${input.requestId}/rsvps/${rsvp.requestId}`;await assert.rejects(()=>getDoc(doc(guestDb,path)));await assert.rejects(()=>getDoc(doc(bob.db,path)));});
 await test('declines and invalid guest inputs are validated',async()=>{await assert.rejects(()=>guest('submitRSVP',{...rsvp,requestId:randomUUID(),partySize:20}),e=>e.code==='functions/invalid-argument');await assert.rejects(()=>guest('submitRSVP',{...rsvp,requestId:randomUUID(),ceremonies:[randomUUID()]}),e=>e.code==='functions/invalid-argument');await assert.rejects(()=>guest('submitRSVP',{...rsvp,requestId:randomUUID(),attendance:'no'}),e=>e.code==='functions/invalid-argument');await guest('submitRSVP',{...rsvp,requestId:randomUUID(),attendance:'no',partySize:0,meal:null});assert.equal((await getDoc(doc(alice.db,`owners/${uid}/events/${input.requestId}`))).data().rsvpStats.declining,1);});
 const book={id:input.requestId,token:replyToken,requestId:randomUUID(),displayName:'Public display name',message:'Wishing you a wonderful celebration.',consent:true};
 await test('guestbook needs consent and pending messages stay private',async()=>{await assert.rejects(()=>guest('submitGuestbook',{...book,consent:false}),e=>e.code==='functions/invalid-argument');assert.equal((await guest('submitGuestbook',book)).data.status,'pending');await guest('submitGuestbook',book);assert.deepEqual((await guest('getGuestbook',{id:input.requestId,token:replyToken})).data.entries,[]);await assert.rejects(()=>getDoc(doc(guestDb,`owners/${uid}/events/${input.requestId}/guestbook/${book.requestId}`)));});
 await test('only owner can moderate; public messages never include private RSVP data',async()=>{const moderation={eventId:input.requestId,entryId:book.requestId,status:'approved'};await assert.rejects(()=>httpsCallable(bob.functions,'moderateGuestbook')(moderation),e=>e.code==='functions/not-found');await invoke('moderateGuestbook',moderation);const entries=(await guest('getGuestbook',{id:input.requestId,token:replyToken})).data.entries;assert.deepEqual(Object.keys(entries[0]).sort(),['displayName','id','message']);assert.equal(entries[0].message,book.message);await invoke('moderateGuestbook',{...moderation,status:'hidden'});assert.equal((await guest('getGuestbook',{id:input.requestId,token:replyToken})).data.entries.length,0);});
 await test('expired guest sessions cannot submit or read the guestbook',async()=>{const {getFirestore:adminStore}=serverRequire('firebase-admin/firestore');const session=adminStore(admin).doc('guestSessions/'+createHash('sha256').update(replyToken).digest('hex'));await session.update({expiresAt:new Date(Date.now()-1000)});await assert.rejects(()=>guest('submitRSVP',{...rsvp,requestId:randomUUID()}),e=>e.code==='functions/permission-denied');await assert.rejects(()=>guest('getGuestbook',{id:input.requestId,token:replyToken}),e=>e.code==='functions/permission-denied');await session.update({expiresAt:new Date(Date.now()+600000)});});
 await test('closed RSVP and guestbook forms reject new submissions',async()=>{await invoke('setGuestSettings',{eventId:input.requestId,rsvpOpen:false,guestbookOpen:false});await assert.rejects(()=>guest('submitRSVP',{...rsvp,requestId:randomUUID()}),e=>e.code==='functions/failed-precondition');await assert.rejects(()=>guest('submitGuestbook',{...book,requestId:randomUUID()}),e=>e.code==='functions/failed-precondition');await invoke('setGuestSettings',{eventId:input.requestId,rsvpOpen:true,guestbookOpen:true});});
 await test('matching private draft IDs cannot overwrite or unpublish another owner invitation',async()=>{const invokeBob=(name,data)=>httpsCallable(bob.functions,name)(data);await invokeBob('createDraft',input);await invokeBob('saveDraft',{...save,requestId:randomUUID(),content:{...content,imagePhotoId:null,galleryPhotoIds:[]}});await assert.rejects(()=>invokeBob('publishInvitation',{eventId:input.requestId,revision:1,requestId:randomUUID(),access:'public'}),e=>e.code==='functions/already-exists');await invokeBob('unpublishInvitation',{eventId:input.requestId,requestId:randomUUID()});await invokeBob('archiveInvitation',{eventId:input.requestId,requestId:randomUUID()});await invokeBob('restoreInvitation',{eventId:input.requestId,requestId:randomUUID()});assert.equal((await guest('getInvitation',{id:input.requestId})).data.content.couple,'Test Couple');});
 await test('unpublished invitations reject RSVP and guestbook access',async()=>{await invoke('unpublishInvitation',action);await assert.rejects(()=>guest('submitRSVP',{...rsvp,requestId:randomUUID()}),e=>e.code==='functions/permission-denied');await assert.rejects(()=>guest('getGuestbook',{id:input.requestId,token:replyToken}),e=>e.code==='functions/permission-denied');});
 await test('contact requests stay local, idempotent and private in emulators',async()=>{const contact={requestId:randomUUID(),name:'Sample Contact',email:'sample@example.test',subject:'Sample question',message:'This is a local test message only.'};assert.equal((await guest('sendContact',contact)).data.status,'local-only');assert.equal((await guest('sendContact',contact)).data.status,'local-only');await assert.rejects(()=>getDoc(doc(guestDb,'contactRequests',contact.requestId)));await assert.rejects(()=>guest('sendContact',{...contact,message:'A changed message.'}),e=>e.code==='functions/already-exists');});
}finally{for(const app of apps){await terminate(getFirestore(app));await deleteApp(app);}await deleteAdmin(admin);}
