import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {createRequire} from 'node:module';
import {initializeApp,deleteApp} from 'firebase/app';
import {getAuth,connectAuthEmulator,signInWithEmailAndPassword} from 'firebase/auth';
import {getFunctions,connectFunctionsEmulator,httpsCallable} from 'firebase/functions';
import {getFirestore,connectFirestoreEmulator,doc,getDoc,terminate} from 'firebase/firestore';
import {getStorage,connectStorageEmulator,ref,getBytes} from 'firebase/storage';
import {enqueueDeletion,processDeletion} from '../functions/deletion.mjs';
const require=createRequire(new URL('../functions/package.json',import.meta.url));
const adminApp=require('firebase-admin/app'),adminStore=require('firebase-admin/firestore'),adminStorage=require('firebase-admin/storage'),adminAuth=require('firebase-admin/auth');
for(const [key,value] of Object.entries({FIREBASE_AUTH_EMULATOR_HOST:'127.0.0.1:9098',FIRESTORE_EMULATOR_HOST:'127.0.0.1:8086',FIREBASE_STORAGE_EMULATOR_HOST:'127.0.0.1:9198'}))if(process.env[key]!==value)throw new Error('Use the isolated local emulators only.');
const admin=adminApp.initializeApp({projectId:'demo-riwaayat',storageBucket:'demo-riwaayat.appspot.com'},'deletion-tests');
const db=adminStore.getFirestore(admin),bucket=adminStorage.getStorage(admin).bucket(),auth=adminAuth.getAuth(admin),clients=[];
async function client(verified=true){const uid='deletion-test-'+randomUUID(),email=uid+'@example.test',password=randomUUID();await auth.createUser({uid,email,password,emailVerified:verified});const app=initializeApp({projectId:'demo-riwaayat',apiKey:'demo-key',storageBucket:'demo-riwaayat.appspot.com'},uid);clients.push(app);const a=getAuth(app);connectAuthEmulator(a,'http://127.0.0.1:9098',{disableWarnings:true});await signInWithEmailAndPassword(a,email,password);const f=getFunctions(app);connectFunctionsEmulator(f,'127.0.0.1',5002);const store=getFirestore(app);connectFirestoreEmulator(store,'127.0.0.1',8086);const storage=getStorage(app);connectStorageEmulator(storage,'127.0.0.1',9198);return {uid,store,storage,call:(name,data)=>httpsCallable(f,name)(data)};}
try{
 const alice=await client(),bob=await client(),unverified=await client(false),event=randomUUID(),copy=randomUUID(),photo=randomUUID(),job=randomUUID();
 const path=`owners/${alice.uid}/events/${event}/photos/${photo}.webp`,eventRef=db.doc(`owners/${alice.uid}/events/${event}`),copyRef=db.doc(`owners/${alice.uid}/events/${copy}`);
 await eventRef.set({ownerId:alice.uid,title:'Disposable deletion fixture',status:'draft'});await copyRef.set({ownerId:alice.uid,title:'Disposable shared-photo copy',status:'draft'});
 await eventRef.collection('photos').doc(photo).set({path,status:'ready'});await copyRef.collection('photos').doc(photo).set({path,status:'ready'});
 await eventRef.collection('rsvps').doc(randomUUID()).set({name:'Test guest'});await eventRef.collection('guestbook').doc(randomUUID()).set({message:'Disposable message'});
 await bucket.file(path).save(Buffer.from('disposable fixture'));await db.doc(`published/${event}`).set({ownerId:alice.uid,eventId:event,revision:'fixture',access:'public',content:{}});
 const sessionId=randomUUID();await db.doc(`guestSessions/${sessionId}`).set({ownerId:alice.uid,eventId:event});
 const request={scope:'invitation',eventId:event,requestId:job,confirmation:'DELETE'};
 await test('deletion rejects foreign owners, unverified users and missing confirmation',async()=>{await assert.rejects(()=>bob.call('requestDeletion',request),e=>e.code==='functions/not-found');await assert.rejects(()=>unverified.call('requestDeletion',request),e=>e.code==='functions/permission-denied');await assert.rejects(()=>alice.call('requestDeletion',{...request,confirmation:'delete'}),e=>e.code==='functions/invalid-argument');});
 await test('deletion requires a recent sign-in',async()=>{await assert.rejects(()=>enqueueDeletion(db,{auth:{uid:alice.uid,token:{auth_time:Math.floor(Date.now()/1000)-600}}},request),e=>e.code==='failed-precondition');assert.equal((await db.doc(`deletionJobs/${job}`).get()).exists,false);});
 await test('queue is idempotent and immediately blocks writes, guest access and private reads',async()=>{assert.equal((await alice.call('requestDeletion',request)).data.status,'queued');assert.equal((await alice.call('requestDeletion',request)).data.id,job);await assert.rejects(()=>alice.call('createDraft',{requestId:randomUUID(),title:'Blocked',templateId:'noor'}),e=>e.code==='functions/failed-precondition');await assert.rejects(()=>alice.call('getInvitation',{id:event}),e=>e.code==='functions/failed-precondition');await assert.rejects(()=>getDoc(doc(alice.store,eventRef.path)));await assert.rejects(()=>getBytes(ref(alice.storage,path)));await assert.rejects(()=>bob.call('requestDeletion',request),e=>e.code==='functions/already-exists');assert.equal(await processDeletion(db,bucket,auth,job),false);});
 await test('partial cleanup preserves its lock and retries while retaining shared photos',async()=>{await db.doc(`deletionJobs/${job}`).update({readyAt:new Date(0)});await assert.rejects(()=>processDeletion(db,{getFiles:async()=>{throw new Error('Injected storage outage');}},auth,job));assert.equal((await db.doc(`deletionJobs/${job}`).get()).data().status,'retry');assert.equal((await db.doc(`owners/${alice.uid}`).get()).data().deletionJob,job);assert.equal(await processDeletion(db,bucket,auth,job),true);assert.equal((await eventRef.get()).exists,false);assert.equal((await eventRef.collection('rsvps').get()).empty,true);assert.equal((await eventRef.collection('guestbook').get()).empty,true);assert.equal((await db.doc(`published/${event}`).get()).exists,false);assert.equal((await db.doc(`guestSessions/${sessionId}`).get()).exists,false);assert.equal((await bucket.file(path).exists())[0],true);assert.equal((await copyRef.get()).exists,true);assert.equal(await processDeletion(db,bucket,auth,job),false);});
 await test('deleted invitation identifiers cannot be resurrected by old retries',async()=>{await assert.rejects(()=>alice.call('createDraft',{requestId:event,title:'Retry',templateId:'noor'}),e=>e.code==='functions/failed-precondition');await assert.rejects(()=>alice.call('duplicateInvitation',{eventId:copy,requestId:event}),e=>e.code==='functions/failed-precondition');assert.equal((await alice.call('getDeletionStatus',{})).data.job.status,'complete');});
 await test('matching event IDs cannot remove another owner publication or session',async()=>{const collision=randomUUID(),requestId=randomUUID(),session=randomUUID();await db.doc(`owners/${alice.uid}/events/${collision}`).set({title:'Disposable private collision'});await db.doc(`published/${collision}`).set({ownerId:bob.uid,eventId:collision});await db.doc(`guestSessions/${session}`).set({ownerId:bob.uid,eventId:collision});await alice.call('requestDeletion',{scope:'invitation',eventId:collision,requestId,confirmation:'DELETE'});await db.doc(`deletionJobs/${requestId}`).update({readyAt:new Date(0)});await processDeletion(db,bucket,auth,requestId);assert.equal((await db.doc(`published/${collision}`).get()).data().ownerId,bob.uid);assert.equal((await db.doc(`guestSessions/${session}`).get()).data().ownerId,bob.uid);});
 await test('account cleanup removes remaining media, account and data, with one worker lease',async()=>{const id=randomUUID();await alice.call('requestDeletion',{scope:'account',requestId:id,confirmation:'DELETE'});await db.doc(`deletionJobs/${id}`).update({readyAt:new Date(0)});const results=await Promise.all([processDeletion(db,bucket,auth,id),processDeletion(db,bucket,auth,id)]);assert.equal(results.filter(Boolean).length,1);assert.equal((await copyRef.get()).exists,false);assert.equal((await bucket.file(path).exists())[0],false);await assert.rejects(()=>auth.getUser(alice.uid),e=>e.code==='auth/user-not-found');assert.equal((await db.doc(`owners/${alice.uid}`).get()).data().closed,true);assert.equal((await db.doc(`deletionJobs/${id}`).get()).data().status,'complete');assert.equal((await alice.call('getDeletionStatus',{})).data.job.status,'complete');await assert.rejects(()=>alice.call('createDraft',{requestId:randomUUID(),title:'Stale token',templateId:'noor'}));assert.equal((await auth.getUser(bob.uid)).uid,bob.uid);});
}finally{for(const app of clients){await terminate(getFirestore(app));await deleteApp(app);}await adminApp.deleteApp(admin);}
