import {useRef,useState,type FormEvent} from 'react';
import {httpsCallable} from 'firebase/functions';
import {configurationError,emulatorMode,services} from './firebase';
import './account.css';
export default function Contact(){const dataRequest=new URLSearchParams(location.search).get('topic')==='data-request';const [busy,setBusy]=useState(false),[error,setError]=useState(''),[status,setStatus]=useState('');const attempt=useRef({key:'',id:''});async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,data=Object.fromEntries(new FormData(form));const key=JSON.stringify(data);if(attempt.current.key!==key)attempt.current={key,id:crypto.randomUUID()};setBusy(true);setError('');setStatus('');try{const result=await httpsCallable(services!.functions,'sendContact')({...data,requestId:attempt.current.id});const state=(result.data as {status:string}).status;if(state==='local-only')setStatus('Saved in the local test inbox. No email was sent.');else if(state==='accepted')setStatus('The email service accepted your message for delivery. Inbox delivery is not yet confirmed.');else throw new Error();form.reset();attempt.current={key:'',id:''};}catch(e){setError((e as {code?:string}).code==='functions/failed-precondition'?'Email delivery is not configured, or this request cannot be retried safely. Your message was not confirmed. Your text is still here.':'We could not confirm your message. Please retry the same details; your text is still here.');}finally{setBusy(false);}}
return <div className="account-page"><header><a className="brand" href="/">❋ riwaayat</a><a href="/account">Your workspace ↗</a></header><main><div className="eyebrow">LET’S TALK</div><h1>{dataRequest?'Your data request':'A little help, a new idea.'}</h1><p>Send a question about your invitation or the service.</p>{emulatorMode&&<p className="account-banner">Local test inbox only · use sample details · no emails are sent</p>}{configurationError?<p>{configurationError}</p>:<section className="account-panel"><p>Your name, email and message are used to respond to your enquiry. Do not include passwords, payment details or private guest information.</p><form onSubmit={submit}><label>Your name<input name="name" required maxLength={100} autoComplete="name" disabled={busy}/></label><label>Reply email<input name="email" type="email" required maxLength={254} autoComplete="email" disabled={busy}/></label><label>Subject<input name="subject" defaultValue={dataRequest?'Data access, correction or deletion request':''} required maxLength={150} disabled={busy}/></label><label>Message<textarea name="message" placeholder={dataRequest?'Tell us whether you are a host or guest, the relevant invitation link, and what you want reviewed. Do not include passwords or identity documents.':undefined} required minLength={10} maxLength={3000} rows={6} disabled={busy}/></label><button className="button primary" disabled={busy}>{busy?'Submitting…':emulatorMode?'Save to local test inbox':'Send message'}</button></form>{error&&<p role="alert" className="account-error">{error}</p>}{status&&<p role="status" className="account-banner">{status}</p>}</section>}<nav className="account-links" aria-label="Policies"><a href="/privacy">Privacy</a><a href="/terms">Terms</a><a href="/data-request">Data requests</a></nav></main></div>;
}


