import {useEffect,useState,type FormEvent} from 'react';
import {onAuthStateChanged,type User} from 'firebase/auth';
import {collection,getDocs} from 'firebase/firestore';
import {services,configurationError} from './firebase';
import {deleteSelectedData} from './delete-data';
import './account.css';
export default function DataControls(){
 const [user,setUser]=useState<User|null>(null),[ready,setReady]=useState(false),[events,setEvents]=useState<{id:string;title:string}[]>([]),[scope,setScope]=useState<'invitation'|'account'>('invitation'),[eventId,setEventId]=useState(''),[confirmation,setConfirmation]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 useEffect(()=>{if(!services){setReady(true);return;}return onAuthStateChanged(services.auth,u=>{setUser(u);setEvents([]);setReady(true);});},[]);
 useEffect(()=>{if(!services||!user?.emailVerified)return;let active=true;getDocs(collection(services.db,'owners',user.uid,'events')).then(rows=>{if(active)setEvents(rows.docs.map(d=>({id:d.id,title:d.data().title})));}).catch(()=>{if(active)setError('Could not load your invitations. Refresh to retry.');});return()=>{active=false;};},[user]);
 async function submit(e:FormEvent){e.preventDefault();if(!services||!user||busy||confirmation!=='DELETE')return;setBusy(true);setError('');setNotice('');try{await deleteSelectedData(services.db,user,scope,eventId);setEvents(old=>old.filter(v=>v.id!==eventId));setEventId('');setConfirmation('');setNotice(scope==='account'?'Account and active invitation data deleted.':'Invitation and its active records deleted.');}catch(e){setError((e instanceof Error?e.message:'Deletion was interrupted.')+' Deletion is not confirmed complete. Keep this page open and retry; completed removals are safe to repeat.');}finally{setBusy(false);}}
 return <div className="account-page"><header><a className="brand" href="/">❋ riwaayat</a><a href="/account">Your workspace ↗</a></header><main><h1>Permanent deletion</h1>{error&&<p role="alert" className="account-error">{error}</p>}{notice&&<p role="status">{notice}</p>}{configurationError?<p>{configurationError}</p>:!ready?<p>Checking account…</p>:!user?<p><a href="/account">Sign in</a> to manage your data.</p>:!user.emailVerified?<p>Verify your email in your workspace first.</p>:<section className="account-panel"><p>This permanently removes the selected invitation, its photos, replies and guestbook entries. Account deletion removes all your invitations and sign-in account. Export any replies you need first.</p><p>Keep this page open until completion. If interrupted, reopen and retry. Downloaded copies, provider records and backups require separate handling through <a href="/data-request">support</a>.</p><form onSubmit={submit}><fieldset disabled={busy}><legend>Choose data to delete</legend><label>Delete<select value={scope} onChange={e=>{setScope(e.target.value as typeof scope);setConfirmation('');}}><option value="invitation">One invitation</option><option value="account">My account and all invitations</option></select></label>{scope==='invitation'&&<label>Invitation<select required value={eventId} onChange={e=>setEventId(e.target.value)}><option value="">Choose invitation</option>{events.map(v=><option key={v.id} value={v.id}>{v.title}</option>)}</select></label>}<label>Type DELETE to confirm<input autoComplete="off" value={confirmation} onChange={e=>setConfirmation(e.target.value)} required pattern="DELETE"/></label><button className="button primary" disabled={confirmation!=='DELETE'||busy||(scope==='invitation'&&!eventId)}>{busy?'Deleting — keep this page open…':'Permanently delete selected data'}</button></fieldset></form><p>Sign in within the last five minutes before deleting. <a href="/account">Manage sign-in</a>.</p></section>}</main></div>;
}
