import { useEffect, useRef, useState, type ReactNode } from 'react';
import { countdownParts, formatEventDate, type InvitationEvent } from './events';
import { MusicControls, Particles, ScratchCard, useReducedMotion } from './invitation-effects';
import './invitation.css';

function Countdown({event}:{event:InvitationEvent}) {
  const [now,setNow]=useState(Date.now);
  useEffect(()=>{let timer:ReturnType<typeof setInterval>|undefined;const update=()=>{clearInterval(timer);setNow(Date.now());if(!document.hidden)timer=setInterval(()=>setNow(Date.now()),1000);};update();document.addEventListener('visibilitychange',update);return ()=>{clearInterval(timer);document.removeEventListener('visibilitychange',update);};},[]);
  const time=countdownParts(event.startsAt,now);
  return <div className="inv-countdown-section"><span className="inv-kicker">{time.started?'THE CELEBRATION HAS BEGUN':'EVERY SECOND, A LITTLE CLOSER'}</span>{!time.started&&<div className="inv-countdown" aria-label="Time remaining until the celebration">{(['days','hours','minutes','seconds'] as const).map(unit=><div key={unit}><strong>{String(time[unit]).padStart(2,'0')}</strong><span>{unit}</span></div>)}</div>}<p>{formatEventDate(event.startsAt,event.timeZone,true)} · {event.timeZone}</p></div>;
}

function DemoRSVP({event}:{event:InvitationEvent}) {
  const [attendance,setAttendance]=useState('yes');
  const [complete,setComplete]=useState(false);
  const result=useRef<HTMLDivElement>(null);
  useEffect(()=>{if(complete)result.current?.focus();},[complete]);
  return <section className="inv-section inv-rsvp" id="rsvp"><div className="inv-section-heading"><span className="inv-kicker">A PLACE AT OUR CELEBRATION</span><h2>{event.id==='bloom'?'Save me a dance.':'Will you join us?'}</h2><p>We would love to have you with us.</p></div><div className="inv-form-panel"><div className="inv-demo-notice"><strong>Try the RSVP · demo only</strong><p>Use sample details. Nothing is sent or saved, and no place is reserved.</p></div>{complete?<div ref={result} tabIndex={-1} className="inv-demo-result"><span aria-hidden="true">✧</span><h3>That’s how your reply will look.</h3><p>Demo complete. Your reply was not sent or stored.</p><button className="inv-button" onClick={()=>setComplete(false)}>Try the form again</button></div>:<form onSubmit={e=>{e.preventDefault();setComplete(true);}}><label>Your name<input name="guestName" required maxLength={100} placeholder="e.g. Sample Guest" autoComplete="off"/></label><fieldset><legend>Will you be joining us?</legend><label className="inv-radio"><input type="radio" name="attendance" value="yes" checked={attendance==='yes'} onChange={()=>setAttendance('yes')}/> Joyfully accept</label><label className="inv-radio"><input type="radio" name="attendance" value="no" checked={attendance==='no'} onChange={()=>setAttendance('no')}/> Regretfully decline</label></fieldset>{attendance==='yes'&&<><div className="inv-form-row"><label>Party size<select name="partySize">{[1,2,3,4,5,6].map(n=><option key={n} value={n}>{n} {n===1?'guest':'guests'}</option>)}</select></label><label>Meal preference<select name="meal"><option>No preference</option><option>Vegetarian</option><option>Vegan</option><option>Halal</option></select></label></div><fieldset><legend>Which moments will you share?</legend>{event.ceremonies.map(c=><label key={c.id} className="inv-radio"><input type="checkbox" name="ceremonies" value={c.id} defaultChecked/>{c.title}</label>)}</fieldset></>}<label>A little note <span>(optional)</span><textarea name="message" maxLength={500} rows={3} placeholder="Your wishes for the celebration…"/></label><button className="inv-button" type="submit">Preview my reply <span aria-hidden="true">↗</span></button></form>}</div></section>;
}

function Gallery({event,sample}:{event:InvitationEvent;sample:boolean}) {
  const [selected,setSelected]=useState<number|null>(null);
  const dialog=useRef<HTMLDialogElement>(null);const trigger=useRef<HTMLElement|null>(null);
  const active=selected!==null;
  useEffect(()=>{if(active){trigger.current=document.activeElement as HTMLElement;dialog.current?.showModal();document.body.style.overflow='hidden';}else{dialog.current?.close();document.body.style.overflow='';trigger.current?.focus();}return ()=>{document.body.style.overflow='';};},[active]);
  return <section className="inv-section" id="moments"><div className="inv-section-heading"><span className="inv-kicker">THE FEELING, IN PHOTOGRAPHS</span><h2>{event.id==='bloom'?'A little moodboard.':'Moments to hold close.'}</h2>{sample&&<p>Sample photography for this design. Your own memories will go here.</p>}</div><div className="inv-gallery">{event.gallery.map((photo,index)=><button key={photo.src} aria-label={`Open photograph ${index+1}`} onClick={()=>setSelected(index)}><img src={photo.src} alt={photo.alt} loading="lazy" width="640" height="800"/><span aria-hidden="true">↗</span></button>)}</div><dialog className="inv-lightbox" ref={dialog} aria-label="Photograph viewer" onCancel={e=>{e.preventDefault();setSelected(null);}} onClick={e=>{if(e.target===dialog.current)setSelected(null);}} onKeyDown={e=>{if(selected===null)return;if(e.key==='ArrowRight'){e.preventDefault();setSelected((selected+1)%event.gallery.length);}if(e.key==='ArrowLeft'){e.preventDefault();setSelected((selected+event.gallery.length-1)%event.gallery.length);}}}>{selected!==null&&<><button className="inv-lightbox-close" onClick={()=>setSelected(null)} aria-label="Close photograph">×</button><img src={event.gallery[selected].src} alt={event.gallery[selected].alt}/><div className="inv-lightbox-controls"><button onClick={()=>setSelected((selected+event.gallery.length-1)%event.gallery.length)} aria-label="Previous photograph">←</button><span aria-live="polite">{selected+1} / {event.gallery.length}</span><button onClick={()=>setSelected((selected+1)%event.gallery.length)} aria-label="Next photograph">→</button></div></>}</dialog></section>;
}

export function Invitation({event,sample=true,ownerPreview=false,responseSection}:{event:InvitationEvent;sample?:boolean;ownerPreview?:boolean;responseSection?:ReactNode}) {
  const reduced=useReducedMotion();
  const [opened,setOpened]=useState(event.effects?.opening===false);
  const [opening,setOpening]=useState(false);
  const [effects,setEffects]=useState(true);
  const gate=useRef<HTMLDialogElement>(null);const heading=useRef<HTMLHeadingElement>(null);
  const ornament=event.id==='noor'?'☾':'❋';
  useEffect(()=>{document.title=`${event.couple} · ${event.name}`;if(event.effects?.opening!==false){gate.current?.showModal();document.body.style.overflow='hidden';}return ()=>{document.body.style.overflow='';};},[event]);
  useEffect(()=>{if(!opening)return;const timeout=setTimeout(()=>setOpened(true),reduced?0:1100);return ()=>clearTimeout(timeout);},[opening,reduced]);
  useEffect(()=>{if(opened){gate.current?.close();document.body.style.overflow='';heading.current?.focus({preventScroll:true});}},[opened]);
  return <div className={`inv-page inv-${event.id}`}>
    <a className="skip-link" href="#inv-main">Skip to invitation</a>
    <Particles kind={event.particle} enabled={opened&&effects&&!reduced&&event.effects?.particles!==false}/>
    <div className="inv-preview-bar"><a href="/#designs">← The collection</a><span>{event.name} · {sample?'SAMPLE INVITATION':ownerPreview?'PRIVATE PREVIEW':'INVITATION'}</span></div>
    <header className="inv-nav"><a className="inv-monogram" href="#inv-main">{sample?(event.id==='royal'?'A & M':event.id==='noor'?'Z & A':'A · 21'):event.couple.split(/\s+/).filter(w=>/^[\p{L}]/u.test(w)).slice(0,2).map(w=>w[0]).join(' · ')}</a><nav aria-label="Invitation navigation">{event.ceremonies.length>0&&<a href="#celebration">The celebration</a>}{event.gallery.length>0&&<a href="#moments">Photographs</a>}<a href="#rsvp">RSVP</a></nav></header>
    <main id="inv-main"><section className="inv-hero"><div className="inv-hero-photo"><img src={event.image} alt={sample?`${event.name} celebration inspiration`:"Celebration cover photograph"} width="900" height="1100" fetchPriority="high"/></div><div className="inv-hero-copy"><span className="inv-kicker">{event.id==='bloom'?'A NEW YEAR OF WONDER':'YOU ARE WARMLY INVITED'}</span><span className="inv-ornament" aria-hidden="true">{ornament}</span><p className="inv-intro">{event.intro}</p><h1 ref={heading} tabIndex={-1}>{event.couple}</h1><p className="inv-note">{event.note}</p><div className="inv-date">{formatEventDate(event.startsAt,event.timeZone)}<span>{event.venue.name}</span></div><a className="inv-button" href="#rsvp">{event.id==='bloom'?'Count me in':'Celebrate with us'} <span aria-hidden="true">↓</span></a></div><div className="inv-hero-bottom" aria-hidden="true">{event.id==='bloom'?'GOOD PEOPLE. GREAT MEMORIES.':'A CELEBRATION OF LOVE & TOGETHERNESS.'}</div></section>
    <Countdown event={event}/>
    {(event.story.length>0||event.quote)&&<section className="inv-section inv-story"><div className="inv-section-heading"><span className="inv-kicker">{event.id==='bloom'?'HERE’S TO MORE':'OUR LITTLE STORY'}</span><h2>{event.id==='bloom'?'A new chapter begins.':'The way we found forever.'}</h2>{event.quote&&<p className="inv-quote">“{event.quote}”</p>}</div><div className="inv-story-grid">{event.story.map((moment,index)=><article key={moment.year}><span className="inv-story-index">0{index+1}</span><small>{moment.year}</small><h3>{moment.title}</h3><p>{moment.text}</p></article>)}</div></section>}
    {event.ceremonies.length>0&&<section className="inv-section inv-celebration" id="celebration"><div className="inv-section-heading"><span className="inv-kicker">COME FOR THE MOMENTS. STAY FOR THE MEMORIES.</span><h2>{event.id==='bloom'?'A lovely little plan.':'The celebration unfolds.'}</h2><p>All times are local to the venue · {event.timeZone}</p></div><div className="inv-itinerary">{event.ceremonies.map((ceremony,index)=><article key={ceremony.id}><span className="inv-ceremony-number">0{index+1}</span><div><time dateTime={ceremony.startsAt}>{formatEventDate(ceremony.startsAt,event.timeZone,true)}</time><h3>{ceremony.title}</h3><p>{ceremony.place}</p></div><span className="inv-attire">{ceremony.attire}</span></article>)}</div></section>}
    {event.effects?.scratch!==false&&(event.hashtag||event.dressCode)&&<section className="inv-section inv-surprise"><div><span className="inv-kicker">A LITTLE SECRET, SEALED WITH LOVE</span><h2>Something just<br/><em>for our people.</em></h2><p>Uncover our celebration hashtag and a little inspiration for what to wear.</p></div><ScratchCard hashtag={event.hashtag} dressCode={event.dressCode}/></section>}
    {event.gallery.length>0&&<Gallery event={event} sample={sample}/>}
    <section className="inv-section inv-venue" id="venue"><div className="inv-venue-image"><img src={event.gallery[2]?.src||event.image} alt={sample?"Celebration inspiration; not a venue photograph":"Celebration photograph"} loading="lazy" width="640" height="800"/><span>{sample?"CELEBRATION INSPIRATION":"A MOMENT TO REMEMBER"}</span></div><div><span className="inv-kicker">MEET US HERE</span><h2>{event.venue.name}</h2><p>{event.venue.address}</p>{sample&&<p className="inv-venue-note">This is a sample invitation. Venue details are for demonstration; no event or booking is confirmed.</p>}<a className="inv-button" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(event.venue.mapQuery)}`} target="_blank" rel="noopener noreferrer">View area on Maps <span aria-hidden="true">↗</span></a></div></section>
    {sample?<DemoRSVP event={event}/>:responseSection||<section id="rsvp" className="inv-section inv-rsvp"><h2>RSVP</h2><p>This is the saved owner preview. Open the published guest link to submit a reply.</p></section>}
    <section className="inv-section inv-faq"><div className="inv-section-heading"><span className="inv-kicker">A FEW THINGS TO KNOW</span><h2>Before you arrive.</h2></div>{[['Can I send a real RSVP here?',sample?'This is a design demonstration. The form does not send or store replies.':ownerPreview?'Open the published guest link to submit a reply.':'Yes. Your reply is saved privately for the host when submissions are open.'],['What should I wear?',event.dressCode],['Are these real event details?',sample?'The names, stories and schedules are sample content.':'These details were supplied by your host. Contact them with any event questions.'],['Can I stop the music or visual effects?','Use the controls at the bottom of the screen. Music starts only when you choose Play and pauses when this tab is hidden. Your device’s reduced-motion preference disables particles.']].map(([question,answer])=><details key={question}><summary>{question}<span aria-hidden="true">+</span></summary><p>{answer}</p></details>)}</section>
    <footer className="inv-footer"><span aria-hidden="true">{ornament}</span><h2>{event.couple}</h2><p>{event.hashtag} · {formatEventDate(event.startsAt,event.timeZone)}</p><a href="/#designs">Made with Riwaayat · Explore the collection ↗</a></footer></main>
    {opened&&(event.effects?.music!==false||event.effects?.particles!==false)&&<aside className="inv-controls" aria-label="Invitation effects">{event.effects?.music!==false&&<MusicControls initial={event.instrument}/>}{event.effects?.particles!==false&&<button className="inv-small-button" onClick={()=>setEffects(!effects)} aria-pressed={!effects} disabled={reduced}>{reduced?'Reduced motion':effects?'Pause particles':'Resume particles'}</button>}</aside>}
    <dialog className={`inv-opening ${opening?'opening':''}`} ref={gate} aria-labelledby="opening-title" onCancel={e=>{e.preventDefault();setOpened(true);}}><div className="inv-opening-content"><a href="/#designs" className="inv-back">← Back to the collection</a><span className="inv-kicker">A LITTLE SOMETHING, JUST FOR YOU</span><h2 id="opening-title">{event.couple}</h2><p>{event.id==='bloom'?'An invitation to celebrate.':'A beginning to remember.'}</p><div className="invite-envelope"><div className="invite-envelope-letter"><span>{ornament}</span><h3>{event.couple}</h3><small>{formatEventDate(event.startsAt,event.timeZone)}</small></div><div className="invite-envelope-back"/><div className="invite-envelope-pocket"/><div className="invite-envelope-flap"/><button className="invite-wax" aria-label="Open invitation" disabled={opening} onClick={()=>setOpening(true)}><span>{sample?(event.id==='royal'?'A M':event.id==='noor'?'Z A':'A'):'✧'}</span></button></div><p className="inv-opening-hint" aria-live="polite">{opening?'Your invitation is unfolding…':'Touch the seal to unfold the story.'}</p><button className="inv-text-button" onClick={()=>setOpened(true)}>Skip opening animation →</button><small className="inv-opening-demo">{sample?'DESIGN PREVIEW · SAMPLE EVENT':ownerPreview?'PRIVATE INVITATION PREVIEW':'AN INVITATION FOR YOU'}</small></div></dialog>
  </div>;
}

export function MissingInvitation(){return <main className="notice"><h1>That invitation isn’t here.</h1><p>Choose Royal Heritage, Noor or Bloom from the collection.</p><a className="button primary" href="/#designs">Back to the collection</a></main>;}
