import './account.css';
import './legal.css';

const privacy = [
  ['Information you provide', 'Hosts provide account details, invitation content and uploaded photos. Guests may provide a name, attendance, party size, meal preference, selected ceremonies and a note. Guestbook entries contain a display name, message and publication consent. Contact requests contain a name, reply email, subject and message. Avoid sensitive information in free-text fields.'],
  ['How information is used', 'Account information supports sign-in and ownership checks. Invitation content displays your celebration. Replies help the host organise attendance. Guestbook messages support moderated celebration messages. Contact details are used to respond to enquiries. Firebase App Check and database access rules help restrict unauthorised requests.'],
  ['Who can see it', 'Published invitation content is accessible through its guest link; passcode invitations also require the passcode. Share links and passcodes carefully. RSVP details are available to the invitation owner, who can export them. Approved messages on public invitations are visible to visitors. Passcode invitation messages remain private to the host. Pending messages are available to the owner for moderation. Service operators and infrastructure providers may process stored data to run the service.'],
  ['Services and browser storage', 'The application uses Firebase Authentication and Firestore for accounts, invitation data and compressed photos. Sign-in uses browser session storage. Production configuration requires Google App Check with reCAPTCHA Enterprise. Contact forms prepare a draft in your email app; the site does not send mail automatically. No analytics integration is enabled. External map links open a separate provider. Production providers, hosting regions and transfer arrangements must be confirmed before launch.'],
  ['Retention and removal', 'There is currently no automatic retention schedule for accounts, invitations, photos, replies, guestbook messages or contact requests. Archiving an invitation preserves its data; unpublishing removes guest access but does not erase stored records. Passcode contents are encrypted in the browser. Previously downloaded copies cannot be revoked. Hosts can remove active invitation data through data controls while keeping the page open until completion. Interrupted cleanup can be retried. Retention periods, backup handling and production deletion checks remain launch requirements.'],
  ['Your choices', 'Hosts can edit invitations, unpublish them, close reply forms and moderate guestbook entries. For access, correction or deletion, use the data request page. Requests require review and may require proportionate ownership checks. Applicable rights and response deadlines depend on the jurisdiction, which is not yet confirmed.']
];
const terms = [
  ['Platform Terms', 'Riwaayat provides digital celebration and wedding invitations. These terms describe the service, account guidelines, and content ownership.'],
  ['Your account and content', 'Keep your account credentials secure and provide accurate invitation details. Only upload photos and content you have permission to use and share. Do not post unlawful, abusive or misleading material, impersonate others, or attempt to bypass access controls.'],
  ['Publishing and guest information', 'Review your invitation before publishing and decide who should receive the link and any passcode. Hosts are responsible for their event arrangements and appropriate handling of guest replies and exported files. Obtain permission where needed before sharing another person’s information or photographs.'],
  ['Replies and moderation', 'Guests should submit accurate responses without including unnecessary private information. Guestbook publication requires consent and host approval. Hosts can close submissions and hide or reject messages. RSVP receipt confirms a saved reply, not a booking, payment or event guarantee.'],
  ['Changes, access and deletion', 'Hosts can save drafts, publish, unpublish and archive invitations. Archiving is reversible and does not delete data. Data removal requests are reviewed separately. The final terms must define service availability, account restrictions, dispute handling and any applicable limitations before launch.'],
  ['Payments and final terms', 'Checkout and paid subscriptions are not implemented in this rebuild. No prices, refunds or cancellation promises are established by this draft. Business details, applicable law and any future commercial terms must be confirmed before offering paid services.']
];

export default function Legal({page}:{page:'privacy'|'terms'|'data-request'}) {
 const request=page==='data-request';
 return <div className="account-page legal-page"><header><a className="brand" href="/">❋ riwaayat</a><a href="/account">Your workspace ↗</a></header><main><div className="eyebrow">YOUR CELEBRATION, YOUR INFORMATION</div><h1>{request?'Request help with your data':page==='privacy'?'Privacy notice':'Terms of service'}</h1><p className="account-banner">Riwaayat Policies · Review our data protection guidelines and platform terms.</p><nav className="account-links" aria-label="Policies"><a href="/privacy" aria-current={page==='privacy'?'page':undefined}>Privacy</a><a href="/terms" aria-current={page==='terms'?'page':undefined}>Terms</a><a href="/data-request" aria-current={request?'page':undefined}>Data requests</a></nav>{request?<section className="legal-section"><h2>Access, correction or deletion</h2><p>You can prepare a request through our contact form. Include whether you are a host or guest, the invitation link if relevant, and which information you want reviewed. For a host account, use your account email as the reply address.</p><p>Do not send passwords, passcodes, identity documents or other guests’ details. We may need to confirm ownership before acting on a request.</p><p>Submitting a request does not delete any data. The local test inbox does not send email. Live request handling and production deletion checks must be ready before launch.</p><a className="button primary" href="/contact?topic=data-request">Prepare a data request ↗</a><h2>Manage your own account</h2><p>Verified hosts can <a href="/data-controls">request permanent account or invitation deletion</a> after a recent sign-in. Keep the page open while cleanup runs; interrupted cleanup can be retried. This removes active invitation records and unused media; independent contact enquiries, exported copies, provider records and backups require separate handling.</p><h2>Remove guest access now</h2><p>Hosts can unpublish an invitation from its editor. This stops new guest access but keeps the saved invitation and responses. Copies already downloaded or exported by others are not removed by unpublishing.</p></section>:(page==='privacy'?privacy:terms).map(([title,body])=><section className="legal-section" key={title}><h2>{title}</h2><p>{body}</p></section>)}<footer><a href="/contact">Contact support</a><a href="/">Back to Riwaayat</a></footer></main></div>;
}
